language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-24
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
  licenses:
    - android-sdk-license-.+

jdk:
  - oraclejdk8

branches:
  except:
    - gh-pages

sudo: false

script:
  - sh ci.sh

notifications:
  email: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle